### ISSUE TITLE
Build fails with gcc 12.1.0

### ISSUE THREAD

**Issue by cbix** [essej/paulxstretch#16]
When trying to build on Linux I'm getting this error:
```
  /home/florian/osamc/archlinux-proaudio/packages/paulxstretch/src/paulxstretch-1.5.3/deps/juce/modules/juce_gui_basics/native/juce_linux_Windowing.cpp:568:50:
  error: ‘exchange’ is not a member of ‘std’

    568 |             const auto wasDarkModeEnabled = std::exchange (darkModeEnabled, XWindowSystem::getInstance()->isDarkModeActive());
        |                                                  ^~~~~~~~

  make[2]: *** [extras/Build/juceaide/CMakeFiles/juceaide.dir/build.make:107:
  extras/Build/juceaide/CMakeFiles/juceaide.dir/__/__/__/modules/juce_gui_basics/juce_gui_basics.cpp.o]
  Error 1
```
Apparently this issue appeared in gcc 12 which may have introduced breaking changes in the standard library...

Compiler version: gcc 12.1.0 on Arch Linux

**Comment by essej** [comment]
I was going to say that the code requires c++-17 and it is already specified in cmake. Not sure what to do about a broken gcc… let me know if you find a workaround

**Comment by cbix** [comment]
@essej got this working by adding
```c
#if __GNUC__ >= 12
  #include <utility>
#endif
```
in `juce_gui_basics.h`

**Comment by baconpaul** [comment]
just fyi : https://forum.juce.com/t/missing-header-in-juce-componentpeer/51665

there's the commit in juce which fixes this but they still have it on develop not in a release. ( I patched surge's juce to cherry pick that )

**Comment by cbix** [comment]
Perfect, using that commit makes more sense indeed. Are you going to add that to the juce subrepo in here as well or wait for upstream juce to realease with that change?

**Comment by essej** [comment]
I will add it here now...

**Comment by essej** [comment]
Done in 1.6.0
