### ISSUE TITLE
Have to reset buffer size to enable playback

### ISSUE THREAD

**Issue by spoisseroux** [essej/paulxstretch#27]
PaulXStrectch 1.6.0 on MacOS 12.4 Apple M1 Pro
Steps to reproduce:
1. Open PaulXStretch
2. Capture audio
3. Try to playback paulstretch audio
4. Audio will not playback unless a buffer size is selected (medium is selected as default, but must be selected again for playback to work)

**Comment by essej** [comment]
Thanks this is a known issue, which I think I have fixed for the next update. In the meantime, a quicker way is to toggle off then on the stretch enable button next to the stretch rate.
